# This workflow will build a golang project
# sample change done
# second change
# one more change
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      DB_PORT: 5434
      TESTMO_PROJECT_ID: 1
      GOTESTSUM_JUNITFILE: tests_results.xml
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...
    
    - name: Install gotestsum
      run: go install gotest.tools/gotestsum@v1.10.0
      
    - name: Install testmo cli
      run: npm install --no-save @testmo/testmo-cli

    - name: Run Go tests 
      run: |
          npx testmo automation:run:submit \
            --instance "$TESTMO_URL" \
            --project-id 1 \
            --tags go \
            --name "Go test run" \
            --source "backend" \
            --results tests_results.xml \
            -- gotestsum # Note space after --
      env:
          TESTMO_URL: ${{ secrets.TESTMO_URL }}
          TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}
      
      
