# This workflow will build a golang project
# sample change done
# second change
# one more change
# test
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}
  GOTESTSUM_JUNITFILE: tests_results.xml

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...
    
    - name: Install gotestsum
      run: go install gotest.tools/gotestsum@v1.10.0
    
    - name: Install testmo cli
      run: make install-testmo

    - name: Add github configs to testmo
      run: |
        npx testmo automation:resources:add-field \
          --name git \
          --type string \
          --value ${GITHUB_SHA:0:7} \
          --resources resources.json
        npx testmo automation:resources:add-link \
          --name build \
          --url "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" \
          --resources resources.json
  
    - name: Run Go tests 
      run: gotestsum
    - name: Upload results to testmo
      run: make testmo-run-go-run
      if: success() || failure()
    - name: test message
      run: echo test
      
      
